---
title: "Preliminary Fit 2"
output:
  html_document: 
    toc: true
    toc_float: true
    theme: "journal"
    css: "website-custom.css"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
library(tidyverse)
library(tidymodels)
library(tune)
library(glmnet)
library(baguette)
library(parsnip)
library(doParallel)
library(vip)
library(pdp)
library(patchwork)
library(ranger)
library(future)
```

# Data 

```{r, include=TRUE}
set.seed(3000)
data <- read_csv(here::here("data", "train.csv")) %>% 
  select(-classification)

data <- dplyr::sample_frac(data, size = 0.01)

sheets <- readxl::excel_sheets(here::here("data",
"fallmembershipreport_20192020.xlsx"))

ode_schools <- readxl::read_xlsx(here::here("data",
"fallmembershipreport_20192020.xlsx"), sheet = sheets[4])

ethnicities <- ode_schools %>%
select(attnd_schl_inst_id = `Attending School ID`,
sch_name = `School Name`,
contains("%")) %>%
janitor::clean_names()
names(ethnicities) <- gsub("x2019_20_percent", "p", names(ethnicities))

data <- left_join(data, ethnicities)
head(data)
colnames(data)
data %>% 
  select(sch_name)
```

# Split and Resample 

```{r, include=TRUE}
set.seed(3000)
data_split <- initial_split(data, strata = "score")

set.seed(3000)
train <- training(data_split)
test <- testing(data_split)

set.seed(3000)
data_cv <- vfold_cv(train, strata = "score")

```

# Preprocess 

```{r, include=TRUE}
rec <- recipe(
    formula = score ~ ., data = train 
  ) %>%
 step_mutate(tst_dt = lubridate::mdy_hms(tst_dt)) %>%
 update_role(contains("id"), ncessch, sch_name, new_role = "id") %>%
 step_novel(all_nominal(), -all_outcomes()) %>%
 step_unknown(all_nominal(), -all_outcomes()) %>%
 step_medianimpute(all_numeric()) %>%
 step_nzv(all_predictors(), freq_cut = 0, unique_cut = 0) %>%
 step_dummy(all_nominal(), -has_role(match = "id"), -all_outcomes()) %>%
 step_nzv(all_predictors())



prep(rec)  
```


# Random Forest 

## Model 

```{r, include=TRUE}

metrics_eval <- metric_set(rmse,
                           rsq,
                           huber_loss)

floor(sqrt(39))

(cores <- parallel::detectCores())

rf_def_mod <-
  rand_forest() %>% 
  set_engine("ranger",
             num.threads = cores, 
             importance = "permutation",  
             verbose = TRUE) %>% 
  set_mode("regression") %>% 
  set_args(mtry = NULL,
           trees = 1000,
           min_n = NULL) 
           

translate(rf_def_mod)

```

## Workflow

```{r, include=TRUE}
rf_wflow <- workflow() %>%
  add_model(rf_def_mod) %>% 
  add_recipe(rec)
```

## Fit

```{r, include=TRUE}
tictoc::tic()
set.seed(3000)
rf_def_res <- fit_resamples(
  rf_wflow,
  data_cv,
  metrics = metrics_eval,
  control = control_resamples(verbose = TRUE,
                              save_pred = TRUE,
                              extract = function(x) x)
                              )
tictoc::toc()

head(rf_def_res)
```

## Best Estimates 

```{r, include=TRUE}
show_best(rf_def_res, "rmse")

show_best(rf_def_res, "rsq") 

show_best(rf_def_res, "huber_loss")
```


# Make Predictions 

## Read in full test data 

```{r, include=TRUE}
full_test <- read_csv(here::here("data", "train.csv"))

head(full_test)
```

## Join full test data 

```{r, include=TRUE}
full_test_join <- left_join(full_test, ethnicities)
```


## Apply Fit Function to Workflow and Full Training 

```{r, include=TRUE}
tictoc::tic()
fit_rf_workflow <- fit(rf_wflow, train)
tictoc::toc()

fit_rf_workflow

sqrt(fit_rf_workflow$fit$fit$fit$prediction.error)
```

```{r, include=TRUE}
preliminary_fit_2 <- predict(fit_rf_workflow, new_data = full_test_join)


head(preliminary_fit_2)
```

```{r, include=TRUE}
pred_frame <- tibble(Id = full_test_join$id, Predict = preliminary_fit_2$.pred)

head(pred_frame)
```

```{r, include=TRUE}
write_csv(pred_frame, "preliminary_fit_2_Thuy_Claire_Jim.csv")
```